# Generated by Django 3.1.2 on 2021-04-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('login_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=15)),
                ('year', models.CharField(max_length=15)),
                ('dept', models.CharField(max_length=6)),
                ('roll_no', models.CharField(max_length=4)),
            ],
        ),
    ]
