# Generated by Django 3.1.2 on 2021-04-09 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_registerform_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerform',
            old_name='image',
            new_name='id_photo',
        ),
    ]
