# Generated by Django 3.1.2 on 2021-04-21 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20210409_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.CharField(max_length=8)),
                ('subject_id', models.CharField(max_length=8)),
                ('exam_date', models.DateField()),
                ('exam_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Subjective_ques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_text', models.CharField(max_length=500)),
                ('mark', models.IntegerField()),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.exam_details')),
            ],
        ),
        migrations.CreateModel(
            name='Obkective_ques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_text', models.CharField(max_length=500)),
                ('option1', models.CharField(max_length=500)),
                ('option2', models.CharField(max_length=500)),
                ('option3', models.CharField(max_length=500)),
                ('option4', models.CharField(max_length=500)),
                ('correct_ans', models.IntegerField()),
                ('mark', models.IntegerField()),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.exam_details')),
            ],
        ),
    ]
