# Generated by Django 3.1.2 on 2021-04-21 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_exam_details_obkective_ques_subjective_ques'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Obkective_ques',
            new_name='Objective_ques',
        ),
    ]
